name: Update Dependency Graph
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
        env:
          PACKAGES_REPOSITORY: https://maven.pkg.github.com/${{ github.repository }}
          PACKAGES_USERNAME: ${{ secrets.GIT_HUB_PACKAGES_ACTOR }}
          PACKAGES_TOKEN: ${{ secrets.GIT_HUB_PACKAGES_TOKEN }}
