name: Publish Ouroboros

on:
  push:
    tags:
      - 1.*

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Publish AAR to GitHub packages
        run: |
          ./gradlew assemble publishAllPublicationsToGitHubPackagesRepository
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PACKAGES_USERNAME: ${{ secrets.PACKAGES_USERNAME }}
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_PASSWORD }}
