name: Publish Ouroboros

on:
  push:
    branches:
      - 'main'
    tags:
      - 1.*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Assemble project
        run: ./gradlew assembleRelease

      - name: Publish AAR to GitHub packages
        run: |
          ./gradlew publishAllPublicationsToGitHubPackagesRepository
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PACKAGES_REPOSITORY: https://maven.pkg.github.com/${{ github.repository }}
          PACKAGES_USERNAME: ${{ github.actor }}
          PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
