name: Publish Ouroboros

on:
  push:
    tags:
      - 1.*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish AAR to GitHub packages
        run: |
          ./gradlew assemble publishAllPublicationsToGitHubPackagesRepository
        if: startsWith(github.ref, 'refs/tags/')
        env:
          PACKAGES_REPOSITORY: https://maven.pkg.github.com/${{ github.repository }}
          PACKAGES_USERNAME: ${{ github.actor }}
          PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

